### ISSUE TITLE
broken with latest MM

### ISSUE THREAD

**Issue by vaniron** [BerndiVader/MythicMobsQuestsModule#1]
Hello, looks like addon stopped working on lates MM/Quests:
http://prntscr.com/f4qnyg
Quite simple error but it doesnt provide anything more just this..

**Comment by BerndiVader** [comment]
Hello @aglarcz ! Build it against Quests 2.7.6 & MythicMobs 4.1.0, let me know if this did it for you.

**Comment by vaniron** [comment]
Tried and not working, same error.

**Comment by BerndiVader** [comment]
You run MythicMobs? Because i cannot replicate this.

**Comment by vaniron** [comment]
Yes and its working fine besides this module:
http://prntscr.com/f4xzdm

**Comment by BerndiVader** [comment]
The only thing i can think of is that somehow Quests is beeing loaded befor MythicMobs. If this really happens, you (maybe) can avoid this by adding a depend to MythicMobs into the Quests.jar. You can do this by open the Quests.jar with your favorite unpacker find the plugin.yml and add MythicMobs to the depend node:
`depend: [Vault, MythicMobs]`

**Comment by vaniron** [comment]
Still not working.. can you provide me with your Quests.jar ? their jenkins is broken so maybe i got corrupted file..

**Comment by BerndiVader** [comment]
Sry for the delay.... pushed the 2.7.6 build made 6.5.2017. But i dont think it will fix your problem. Please post your whole startuplog. I am very sure that the problem is because MythicMobs beeing loaded afterwards

**Comment by vaniron** [comment]
Its working fine, problem was that i downloaded your addon wrongly in my browser. Sorry for that and thanks for your time.
