### ISSUE TITLE
Killing Mobs doesn´t count for the quest

### ISSUE THREAD

**Issue by zippoking** [BerndiVader/MythicMobsQuestsModule#13]
Hey,

so i tried this module today but i can´t figure it out how it works.

This is my quest:
https://pastebin.com/ynYTTKxs

This is my event:
https://pastebin.com/e9uGQKv3

This is my mob:
https://pastebin.com/xv8mEC9M

Here are the steps of my quest:
1. Talk to NPC Werner and take quests
2. Talk again to him to trigger stage 2
3. In stage 2 event is activated (so the CaveSpider spawns)
4. The the user goes into the area where the spider is and kills her
5. The Kill does not count? Why? 

Can you help me out here? Am i missing something? Everthing seems to be working, except the Kill count. 
I am using Quests 3.2.6-b266

Best regards
Zippoking

**Comment by BerndiVader** [comment]
Hello! Thanks for the report. You can solve this if you use "ANY" instead of "any" or use the latest build [MythicMobsQuestModule](https://github.com/BerndiVader/MythicMobsQuestsModule/blob/master/MythicMobsQuests.jar) i`ve added ignore casesensitive in case of "any".

**Comment by zippoking** [comment]
I don´t know what to say :-D.

Thank you so much! I already tested it!
What a difference casesensitive can make^^.
