### ISSUE TITLE
EntityDeathEvent issues

### ISSUE THREAD

**Issue by PengBread** [BerndiVader/MythicMobsQuestsModule#14]
Killed 1 mythicmobs it cause this issue and the quest count was not added. "stuck on 0/30 mobs killed"
https://pastebin.com/VKsUeQBD

**Comment by BerndiVader** [comment]
do you use the latest module build? looks like you use a version not compatible with quests 2.3.7

**Comment by SXRWahrheit** [comment]
Pull the module again, I had this error at first but mine works now.
