### ISSUE TITLE
Quests dont count MM mobs, unsure why.

### ISSUE THREAD

**Issue by Kainzo** [BerndiVader/MythicMobsQuestsModule#17]
Shouldnt this function? Running MM 4.3+

> t1a_basic:
    name: Kill Unforgiven Husks
    redo-delay: 28800
    npc-giver-id: 94
    ask-message: Go kill the Unforgiven Husks!
    finish-message: You killed Unforgiven Husks! Here's some coin and exp!
    stages:
      ordered:
        '1':
          custom-objectives:
            t1a_basic:
              name: Kill MythicMobs Objective
              count: 10
              data:
                Mob Level: '0'
                Mob Faction: UNF
                Internal Mobnames: ANY
                Notifier enabled: 'true'
                Notifier msg: Killed %c% out of %s%
                Objective Name: Kill Unforgiven Husks!
          death-event: DeathFail
          finish-event: GoodJob
    rewards:
      money: 10`

**Comment by BerndiVader** [comment]
hi kainzo! thanks for reporting! i tried this quest: 

```
  t1a_basic:
    name: Kill Unforgiven Husks
    redo-delay: 5
    npc-giver-id: 0
    ask-message: Go kill the Unforgiven Husks!
    finish-message: You killed Unforgiven Husks! Here's some coin and exp!
    stages:
      ordered:
        '1':
          custom-objectives:
            t1a_basic:
              name: Kill MythicMobs Objective
              count: 10
              data:
                Mob Level: '0'
                Mob Faction: UNF
                Internal Mobnames: ANY
                Notifier enabled: 'true'
                Notifier msg: Killed %c% out of %s%
                Objective Name: Kill Unforgiven Husks!
    death-event: DeathFail
    finish-event: GoodJob
    rewards:
      money: 10
```

and it worked. Maybe your issue is in the yaml format?

**Comment by Kainzo** [comment]
It may be... this startup log.  I think I may be failing at something here.  (The YML formatting was wrong, my paste wasnt right to you, I think I was really tired and just didnt format it, I've worked with YML for 5+ years)
https://paste2.org/aVV3eGK3

**Comment by BerndiVader** [comment]
Looks like the mythicmobs plugin isnt present yet, where quests load and init the modules. I change it so that the module get the mythicmobs instance only if its needed and not at module init. This might fix your issue.

**Comment by Kainzo** [comment]
Is there a dev buidl available? Do I just need to update Quests?

**Comment by Kainzo** [comment]
https://paste2.org/16Wn1BzD

**Comment by BerndiVader** [comment]
Like said, the issue you have is that Quests load befor MythicMobs. The module loader close Quests too if there was a problem in any of the modules... I tried to run quests befor mythicmobs with the latest module build and it works fine.

**Comment by Kainzo** [comment]
I grabbed the latest.. this is really odd... should there be a soft-depend here from Quests > MM?

**Comment by Kainzo** [comment]
Any update on this? does this work with BetonQuest?

**Comment by BerndiVader** [comment]
The lastest build should work even if quests loaded before mythicmobs. To solve this proper, make sure quests plugin.yml **dont** have an entry like `loadbefore: [MythicMobs]` plus make sure that mythicmobs plugin.yml have the entry `loadbefore: [Quests]`

For betonquest support use https://github.com/BerndiVader/bqMythicMobs

**Comment by Kainzo** [comment]
Will give that a try, thanks man!

**Comment by Kainzo** [comment]
I feel like there may be something wrong on Benton Quests side... I'll go ahead and send this to him.
@BerndiVader

**Comment by Kainzo** [comment]
so from what I see on load now... it says it cant ghet MM
[14:09:23] [Server thread/INFO]: [Quests] Loaded Module: MythicMobs Conditions Require by BerndiVader, idea Wahrheit
[14:09:23] [Server thread/WARN]: Not able to get MythicMobs.

**Comment by BerndiVader** [comment]
Thats because, why so ever your Quests plugin load before MythicMobs. That message is just a warning, that the quest module wasnt able to get the mythicmobs instance. The module will try again if the instance is needed. Therefore you should not have any more troubles, aslong as mythicmobs really loads.
