### ISSUE TITLE
Notifier msg no work

### ISSUE THREAD

**Issue by Mrkhris** [BerndiVader/MythicMobsQuestsModule#27]
Mythismobs - MythicMobs-4.5.1
Quests - 3.6.0-b610
Citizens - 2.0.24-SNAPSHOT (build 1605)
Vault - 1.7.1-b91
Spigot 1.12.1 and 1.13.2

"Notifier msg" is not displayed
I even reinstalled all the files again and inserted your original quest, which is on GitHub
![51263850-24046e80-19c6-11e9-9168-9bc35735ae4d](https://user-images.githubusercontent.com/46727551/51264507-bbb68c80-19c7-11e9-8e6c-53955bef6002.png)
![51263850-24046e80-19c6-11e9-9168-9bc35735ae4d](https://user-images.githubusercontent.com/46727551/51264709-2cf63f80-19c8-11e9-9b34-f668c2d52df3.png)

My config quests
![51263850-24046e80-19c6-11e9-9168-9bc35735ae4d](https://user-images.githubusercontent.com/46727551/51264596-f0c2df00-19c7-11e9-82ee-482c8a0f1051.png)

**Comment by BerndiVader** [comment]
i tried that quest and it works. please take care that if you kill the mob it requires some conditions to count: wear no armor, no other player around, hit the mob always and only with a wooden axe and no other player ever damaged the mob.
