### ISSUE TITLE
Quests Journal

### ISSUE THREAD

**Issue by Mrkhris** [BerndiVader/MythicMobsQuestsModule#28]
In the old version of the module was the opportunity in the journal to see how many mobs you need to kill and how many have been killed, you deleted it?

If so, can you return it to the module? That was very helpful.

Just now when it is not in the journal, I find it hard to navigate how many mobs need to kill, especially if I'm not doing the quest right away
![ggs-1awkgpw](https://user-images.githubusercontent.com/46727551/51266680-f5d65d00-19cc-11e9-99c8-f15f01367cc3.jpg)

**Comment by BerndiVader** [comment]
Thanks for reporting. This happens if you use questadmin reset to clear the quests. thats an quests related issue.

**Comment by tiradorus** [comment]
Same issue here.
Mrkhris isn't the only-one affected ^^

Server-version: 1.8.8
Quest Version: 3.6.0 B610

**Comment by PikaMug** [comment]
@Mrkhris What is your Quests version? If you're on a Quests 3.6.0 dev build, you'll need to download the following version of MythicMobsQuestsModule:
https://github.com/BerndiVader/MythicMobsQuestsModule/blob/8a27d96d62cd1b1fc223a007fe30b0a8c532a1e1/MythicMobsQuests.jar

Edit: Same goes for you @tiradorus

**Comment by tiradorus** [comment]
@FlyingPikachu 

Wow! a version that works? oO is that a dream? :D
However, still the same issue with the journal ^^' no KillCounter, even with Quest 629 and the merged version of Mythics =)

**Comment by Mrkhris** [comment]
The problem is not reset quests through questadmin. I just started the server and selected the quest, that's what I get

![sjzaxihrexq](https://user-images.githubusercontent.com/46727551/51753043-eb514d00-20c9-11e9-83e9-21f5dec5bc18.jpg)

My quests
![sjzaxihrexq](https://user-images.githubusercontent.com/46727551/51753220-4f741100-20ca-11e9-95d0-94c8a5689fe5.jpg)

As we can see, the journal displays only the name of the mob I mentioned in the quest

My setting:
Quests - 3.6.0 #629
Latest version MythicMobsQuestsModule
![sjzaxihrexq](https://user-images.githubusercontent.com/46727551/51753378-a7ab1300-20ca-11e9-825f-38e1594e6ed5.jpg)

I need to receive a message as before on version 1.12. It should look like:
![1bjmz8f8k_8](https://user-images.githubusercontent.com/46727551/51753909-08871b00-20cc-11e9-8263-356869791d2b.jpg)
I translated this inscription into my own language, but it means "0/15 [Lvl.1] Resident - killed"

**Comment by Mrkhris** [comment]
![51755589-1ccd1700-20d0-11e9-92a2-353a2954dda5](https://user-images.githubusercontent.com/46727551/51756336-d24c9a00-20d1-11e9-9d82-9a316aa8c144.jpg)

Of course it will not work, because it is simply absent  :)

Be careful, and I advise you to fix the bug!
I fixed it yourself, just by edited a line

![1bjmz8f8k_8](https://user-images.githubusercontent.com/46727551/51755736-72a1bf00-20d0-11e9-9ed8-8e644ada3390.jpg)

After you look and understand what is wrong, close the ticket

**Comment by BerndiVader** [comment]
Ok now i understand. I removed the %count% to have it optional. Do have it back just add %count% into the objective name.  Look at the quest below, particularly the Objective Name:

```
quests:
  example_quest_1:
    name: super example quest 1
    redo-delay: 3
    ask-message: bla bla bla
    finish-message: blubb blubb blubb
    stages:
      ordered:
        '1':
          custom-objectives:
            custom1:
              name: Kill MythicMobs Objective
              count: 3
              data:
                Mob Level: '0'
                Mob Faction: ANY
                TargetConditions: NONE
                Objective Name: blubb example blubb %count%
                Internal Mobnames: potato
                Notifier enabled: 'true'
                Conditions: NONE
                Notifier msg: You killed %c% out of %s% potatos.
```

**Comment by Mrkhris** [comment]
Great, now I understand! Can I ask you one more question? It's a bit off topic, but I don't want to open a new ticket for it. Can I change the color of this inscription in any way? I don't want it to be green

**Comment by tiradorus** [comment]
Yes you can use § instead of & into the config, like that:

Objective Name: §4- Monstres à tuer -   §cZombifiac distordu.


But! i've found a bug ... once again xD
The "questadmin reset" don't reset MythicMobs Objective ... ehhh, no, it reset, but when you re-Take the quest, then you gain 2 by 2 the killCount. or 5 by 5 etc etc.

Even more!
The quests stacks each others, example, you have done 7 quests with MythicObjective, then when you start the 8th, then you gain 8 by 8 on the killcounter

**Comment by BerndiVader** [comment]
This is solved with https://github.com/FlyingPikachu/Quests/pull/652

**Comment by PikaMug** [comment]
@BerndiVader Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
