### ISSUE TITLE
Make plugin compatible with last version of quest, (the B620)

### ISSUE THREAD

**Issue by tiradorus** [BerndiVader/MythicMobsQuestsModule#29]
hi BerndiVader
I've seen that you've done an update of you plugin, and update compatible with the dev build of quest the 'B613' with this extension: BerndiVader/MythicMobsQuestsModule@4a3c951

BUT! here is the problem:

The plugin quests, on B613, load modules after quests, so modules like yours don't work
FlyingPikachu have solve the issues on B614, so one version later xD
But yours isn't compatible on B614!

Please xD make it compatible with quests B620, to close this infernal system ^^ I just want a stable version of MMQuests and Quests each other, after that, i will let it all like that, i don't touch anything else, but i need a stable version T_T

Actualy, quests have solve some important issues, and i can't update because not compatible with your extension xD

Thank you for reading, have a nice day!

**Comment by BerndiVader** [comment]
Hello! This update, atleast is running with 3.6.0 but still there are issues, like the ingame editor dont work anymore and also its prints out the whole options for the objectives.... https://github.com/BerndiVader/MythicMobsQuestsModule/commit/9a79561215c70423d2362c2dd14f983d87c5aad9

**Comment by PikaMug** [comment]
This issue can be resolved by merging https://github.com/BerndiVader/MythicMobsQuestsModule/pull/30
