### ISSUE TITLE
Errors.

### ISSUE THREAD

**Issue by Kainzo** [BerndiVader/MythicMobsQuestsModule#3]
MM version = 4.1.0
Quests = 2.7.6
Latest Module in the modules folder.
This doesnt work.  Config example > https://paste2.org/emsedpH7
Console > https://paste2.org/naA6zsvf

**Comment by BerndiVader** [comment]
The config is wrong. I update the readme.

```
  custom1:
    name: mmtest
    ask-message: kill me some mythicmobs
    finish-message: welldone!
    stages:
      ordered:
        '1':
          custom-objectives:
            custom1:
              name: Kill MythicMobs Objective
              count: 1
              data:
                Mob Level: '0'
                Objective Name: Kill any MythicMob
                Internal Mobnames: ANY
```

**Comment by SXRWahrheit** [comment]
I just submitted #4, which should further help clarify implementation, @Kainzo.

**Comment by BerndiVader** [comment]
@Kainzo I close this now. guess @SXRWahrheit fixed it with his new instruction readme.
