### ISSUE TITLE
MythicMobsQuestsModule not working on spigot 1.13.2

### ISSUE THREAD

**Issue by miglas** [BerndiVader/MythicMobsQuestsModule#38]
I got this error when player kill mobs.
https://pastebin.com/VJXBqzf6
my server version spigot 1.13.2 mythicmobs 4.9.0 mythicmobs-module 3.7.7

**Comment by BerndiVader** [comment]
Hi! please consider that i only support free versions of mm. the module works fine with mm 4.7.2 and the latest quests. if you need premium try this fork: https://github.com/Tirco/MythicMobsQuestsModule

**Comment by miglas** [comment]
Okay, I understood this matter.
Thank you for replying and keep it up your great job!

**Comment by miglas** [comment]
Sorry to bother you again.
Where Can I download fork?
The fork version seems failed build.
and Where should I write bug if I found with using fork?

**Comment by BerndiVader** [comment]
Hi! With the lastest release its compatible with >4.7,2. If something is wrong let me know, if its fixed close the issue. Thanks.

**Comment by miglas** [comment]
The last build is works perfectly with mythicmobs 4.8.0 and 4.9.0.
This plugin plays a significant role for my server. It was very helpful, Thank you so much!
