### ISSUE TITLE
Progress Tracker

### ISSUE THREAD

**Issue by jakovjj** [BerndiVader/MythicMobsQuestsModule#45]
I think that the Addon should be updated to work for the newer versions and so the quests journal and the placeholder for it works. I have the objective for quests on my boss bar and currently I can only make my own objective that I want the players to see and I have no way of it being progressive like the normal ones (e.g. Kill Zombies 0/10 and it updating after every kill).

**Comment by BerndiVader** [comment]
Hello! You can name the objective "Kill Zombies %count%" and you have a counter added to it.

**Comment by jakovjj** [comment]
Wow, that helps a ton, thank you!
