### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by QueenKisaki** [BerndiVader/MythicMobsQuestsModule#5]
Hello not sure why I'm getting this error https://pastebin.com/v7H1kfqS
Using Quests 2.7.6
mm 4.1.0

This also happens with the custommobs plugin too so I'm not sure if its the modules or the quests plugin itself.

**Comment by QueenKisaki** [comment]
Im an idiot and put the jar in the wrong place. Sorry. 

After moving it though I was still getting that error. Have not tested to see if the quests work or not, server is not open yet so im in no rush.

**Comment by BerndiVader** [comment]
erm. no you not!

after moving it you to _plugins\Quests\modules_ you still get the error?

**Comment by QueenKisaki** [comment]
Yea I still get the same error and it's in the correct folder. https://pastebin.com/muHeh5FC is full start up. luckily the error starts at line 13 lol. Ive been getting alot of these errors since updating to 1.11.2 with other plugins.

**Comment by BerndiVader** [comment]
Maybe you still have a copy of it in _plugins_ folder? At least that is what the error says.

` ERROR Could not load 'plugins/QuestMMKillObjective.jar' in folder 'plugins'`

**Comment by QueenKisaki** [comment]
oml I thought I removed that before uploading correctly. I'm so sorry and thank you!
