### ISSUE TITLE
Quests updated but

### ISSUE THREAD

**Issue by QueenKisaki** [BerndiVader/MythicMobsQuestsModule#6]
now that quests was updated, it is not reading that the module is there. I messaged pikachu regarding the matter but I'm not sure where the issue is coming from. https://pastebin.com/kxMWbMbA 

I removed and reinstalled the module and restarted my server but it still doesn't show up.

**Comment by BerndiVader** [comment]
Hello! Thx for reporting! But i fear its a bug in quests itself. None of the modules are loading anymore.

**Comment by BerndiVader** [comment]
Hello! This is now fixed in Quests 2.8.5 or later: http://ci.ac3-servers.eu/job/Quests/
