### ISSUE TITLE
Is there a way to make the counter in chat update as a mob is killed?

### ISSUE THREAD

**Issue by CyberDioxide** [BerndiVader/MythicMobsQuestsModule#9]
I'm sorry if this has been asked before, but is it possible to make the Counter in chat update each time a mob is killed? 
For example,
Kill <MobName> Counter 0/16
If I were to kill <MobName> could the counter in chat go
Kill <MobName> Counter 1/16?
Thanks in advance!

**Comment by BerndiVader** [comment]
Hello! I added "Notifier enabled" and "Notifier msg" to the lastest build. Please test if it works for you.

**Comment by CyberDioxide** [comment]
Thank you so much!
I really appreciate the fast reply.
It works great!
